language: php

php:
  - '7.4'

addons:
  sonarcloud:
    organization: "assoconnect"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - php ./vendor/bin/phpcs
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml --log-junit ./tests/logs/phpunit.report.xml
  - 'if [ ! -z "$SONAR_TOKEN" ]; then sonar-scanner; fi'
